import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { CompResult, SubjectProperty } from '@/types/property';
import { formatCurrency, formatDate } from './utils';

interface ExportData {
  subject: SubjectProperty;
  comps: CompResult[];
  adjustments?: {
    [compId: string]: {
      bedroom: number;
      bathroom: number;
      sqft: number;
      age: number;
      other: number;
    };
  };
  indicatedValue?: number;
}

/**
 * Export comp grid to PDF
 */
export function exportToPDF(data: ExportData): void {
  const { subject, comps, adjustments, indicatedValue } = data;
  const doc = new jsPDF('landscape');

  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Comparable Sales Analysis', pageWidth / 2, 15, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 22, { align: 'center' });

  // Subject Property Section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Subject Property', 14, 35);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const subjectInfo = [
    `Address: ${subject.address}, ${subject.city}, ${subject.state} ${subject.zip}`,
    `Type: ${subject.propertyType} | Beds: ${subject.bedrooms} | Baths: ${subject.bathrooms} | Sq Ft: ${subject.sqft.toLocaleString()} | Year: ${subject.yearBuilt}`,
  ];
  doc.text(subjectInfo, 14, 42);

  // Comparable Sales Table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Comparable Sales', 14, 58);

  const tableData = comps.map((comp, index) => [
    `Comp ${index + 1}`,
    comp.address,
    `${comp.city}, ${comp.state}`,
    formatDate(comp.saleDate),
    formatCurrency(comp.salePrice),
    `${comp.bedrooms}/${comp.bathrooms}`,
    comp.sqft.toLocaleString(),
    `$${comp.pricePerSqft}`,
    `${comp.distanceMiles.toFixed(2)} mi`,
  ]);

  autoTable(doc, {
    startY: 62,
    head: [['#', 'Address', 'City/State', 'Sale Date', 'Sale Price', 'Bed/Bath', 'Sq Ft', '$/SqFt', 'Distance']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [59, 130, 246], fontSize: 9 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 45 },
      4: { halign: 'right' },
      6: { halign: 'right' },
      7: { halign: 'right' },
    },
  });

  // Adjustments Table (if provided)
  if (adjustments && Object.keys(adjustments).length > 0) {
    const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY || 100;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Price Adjustments', 14, finalY + 15);

    const adjTableData = comps.map((comp, index) => {
      const adj = adjustments[comp.id] || { bedroom: 0, bathroom: 0, sqft: 0, age: 0, other: 0 };
      const totalAdj = adj.bedroom + adj.bathroom + adj.sqft + adj.age + adj.other;
      const adjustedPrice = comp.salePrice + totalAdj;

      return [
        `Comp ${index + 1}`,
        formatCurrency(comp.salePrice),
        formatAdjValue(adj.bedroom),
        formatAdjValue(adj.bathroom),
        formatAdjValue(adj.sqft),
        formatAdjValue(adj.age),
        formatAdjValue(adj.other),
        formatAdjValue(totalAdj),
        formatCurrency(adjustedPrice),
      ];
    });

    autoTable(doc, {
      startY: finalY + 19,
      head: [['#', 'Sale Price', 'Bedroom', 'Bathroom', 'Sq Ft', 'Age', 'Other', 'Net Adj.', 'Adjusted Price']],
      body: adjTableData,
      theme: 'striped',
      headStyles: { fillColor: [59, 130, 246], fontSize: 9 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
        3: { halign: 'right' },
        4: { halign: 'right' },
        5: { halign: 'right' },
        6: { halign: 'right' },
        7: { halign: 'right' },
        8: { halign: 'right' },
      },
    });
  }

  // Indicated Value
  if (indicatedValue) {
    const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY || 150;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Indicated Value: ${formatCurrency(indicatedValue)}`, 14, finalY + 15);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by Comp Search Tool', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save
  const filename = `comp-analysis-${subject.address.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${Date.now()}.pdf`;
  doc.save(filename);
}

/**
 * Export comp grid to Excel
 */
export function exportToExcel(data: ExportData): void {
  const { subject, comps, adjustments, indicatedValue } = data;

  // Subject Property Sheet
  const subjectData = [
    ['SUBJECT PROPERTY'],
    ['Address', subject.address],
    ['City', subject.city],
    ['State', subject.state],
    ['ZIP', subject.zip],
    ['Property Type', subject.propertyType],
    ['Bedrooms', subject.bedrooms],
    ['Bathrooms', subject.bathrooms],
    ['Sq Ft', subject.sqft],
    ['Year Built', subject.yearBuilt],
  ];

  // Comparable Sales Sheet
  const compHeaders = [
    'Comp #',
    'Address',
    'City',
    'State',
    'ZIP',
    'Sale Date',
    'Sale Price',
    'Bedrooms',
    'Bathrooms',
    'Sq Ft',
    '$/Sq Ft',
    'Year Built',
    'Property Type',
    'Distance (mi)',
    'Days on Market',
    'Similarity Score',
  ];

  const compData = comps.map((comp, index) => [
    index + 1,
    comp.address,
    comp.city,
    comp.state,
    comp.zip,
    comp.saleDate,
    comp.salePrice,
    comp.bedrooms,
    comp.bathrooms,
    comp.sqft,
    comp.pricePerSqft,
    comp.yearBuilt,
    comp.propertyType,
    comp.distanceMiles,
    comp.daysOnMarket,
    comp.similarityScore,
  ]);

  // Adjustments Sheet
  const adjHeaders = [
    'Comp #',
    'Address',
    'Sale Price',
    'Bedroom Adj',
    'Bathroom Adj',
    'Sq Ft Adj',
    'Age Adj',
    'Other Adj',
    'Net Adjustment',
    'Adjusted Price',
  ];

  const adjData = comps.map((comp, index) => {
    const adj = adjustments?.[comp.id] || { bedroom: 0, bathroom: 0, sqft: 0, age: 0, other: 0 };
    const totalAdj = adj.bedroom + adj.bathroom + adj.sqft + adj.age + adj.other;
    const adjustedPrice = comp.salePrice + totalAdj;

    return [
      index + 1,
      comp.address,
      comp.salePrice,
      adj.bedroom,
      adj.bathroom,
      adj.sqft,
      adj.age,
      adj.other,
      totalAdj,
      adjustedPrice,
    ];
  });

  // Summary row
  if (indicatedValue) {
    adjData.push([]);
    adjData.push(['', '', '', '', '', '', '', '', 'Indicated Value:', indicatedValue]);
  }

  // Create workbook
  const wb = XLSX.utils.book_new();

  // Add sheets
  const wsSubject = XLSX.utils.aoa_to_sheet(subjectData);
  XLSX.utils.book_append_sheet(wb, wsSubject, 'Subject Property');

  const wsComps = XLSX.utils.aoa_to_sheet([compHeaders, ...compData]);
  XLSX.utils.book_append_sheet(wb, wsComps, 'Comparable Sales');

  const wsAdj = XLSX.utils.aoa_to_sheet([adjHeaders, ...adjData]);
  XLSX.utils.book_append_sheet(wb, wsAdj, 'Adjustments');

  // Set column widths
  wsComps['!cols'] = [
    { wch: 8 },  // Comp #
    { wch: 30 }, // Address
    { wch: 15 }, // City
    { wch: 8 },  // State
    { wch: 10 }, // ZIP
    { wch: 12 }, // Sale Date
    { wch: 12 }, // Sale Price
    { wch: 10 }, // Bedrooms
    { wch: 10 }, // Bathrooms
    { wch: 10 }, // Sq Ft
    { wch: 10 }, // $/Sq Ft
    { wch: 10 }, // Year Built
    { wch: 15 }, // Property Type
    { wch: 12 }, // Distance
    { wch: 12 }, // Days on Market
    { wch: 12 }, // Similarity
  ];

  // Save file
  const filename = `comp-analysis-${subject.address.replace(/[^a-z0-9]/gi, '-').toLowerCase()}-${Date.now()}.xlsx`;
  XLSX.writeFile(wb, filename);
}

// Helper function
function formatAdjValue(value: number): string {
  if (value === 0) return '-';
  const sign = value > 0 ? '+' : '';
  return `${sign}${formatCurrency(value)}`;
}
